version: 2.1
jobs:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:v0.8.0
    steps:
      - checkout
      - run:
          name: Run shellcheck
          command: find . -type f \( -name "*.sh" -o -path "*/bin/*" \) ! -name '*.jq' | xargs -t shellcheck

  build-stack:
    parameters:
      stack-version:
        type: enum
        enum: ["18", "20", "22", "18-cnb", "20-cnb", "22-cnb"]
    machine:
      image: ubuntu-2204:2022.04.1
    environment:
      IMAGE_TAG: heroku/heroku:<< parameters.stack-version >>
      PRIVATE_IMAGE_TAG: heroku/heroku-private:<< parameters.stack-version >>
      STACK: heroku-<< parameters.stack-version >>
    steps:
      - checkout
      - run:
          name: Build images
          command: bin/build.sh $STACK $IMAGE_TAG $IMAGE_TAG-build
      - run:
          name: Check that the generated files are in sync
          command: |
            status="$(git status --porcelain)"
            if [[ -n "$status" ]]; then
              echo "Generated files differ from checked-in versions! Run bin/build.sh to regenerate them locally."
              echo -e "\nChanged files:\n${status}\n"
              exit 1
            fi
      - when:
          condition:
            or:
              - equal: [ main, << pipeline.git.branch >> ]
              - << pipeline.git.tag >>
          steps:
            - run:
                name: Publish to Docker Hub
                command: bin/publish-to-dockerhub.sh
      - when:
          condition: << pipeline.git.tag >>
          steps:
            - run:
                name: Convert docker image and release to Heroku staging
                command: bin/convert-and-publish-to-heroku.sh

workflows:
  build:
    jobs:
      - shellcheck:
          filters:
            # Enable for release tags (by default all tags are ignored).
            tags:
              only: /^v.*/
      - build-stack:
          name: build-stack-heroku-<< matrix.stack-version >>
          requires:
            - shellcheck
          filters:
            tags:
              only: /^v.*/
          matrix:
            parameters:
              stack-version: ["18", "20", "22"]
      - build-stack:
          name: build-stack-heroku-<< matrix.stack-version >>
          requires:
            - build-stack-heroku-18
            - build-stack-heroku-20
            - build-stack-heroku-22
          filters:
            tags:
              only: /^v.*/
          matrix:
            parameters:
              stack-version: ["18-cnb", "20-cnb", "22-cnb"]
